FROM alpine
RUN apk add --update nodejs nodejs-npm
WORKDIR /usr/src/app
COPY ./apis/TypeScript/Nest .

RUN printf "npm run typeorm migration:run\nexport NODE_OPTIONS=--max_old_space_size=250\nnode dist/src/main\n" > entrypoint.sh

RUN addgroup -S 1001 && adduser -S 1001 -G 1001
USER 1001
EXPOSE 8000
CMD ["/bin/sh", "entrypoint.sh"]
