FROM quay.io/quarkus/quarkus-distroless-image:1.0
WORKDIR /work/
COPY apis/java/quarkus/target/*-runner /work/application

EXPOSE 8000
USER nonroot

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
