name: postgres-backup-image-builder

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/nr-arch-templates
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}

on:
  workflow_dispatch:

jobs:
  build-postgres-backup-image:
    name: Build Postgres Backup container image.
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: Metabase
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: "docker-remote.artifacts.developer.gov.bc.ca"
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Backup image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ env.IMAGE_REGISTRY }}/postgres-backup:v1"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: |
            ./Metabase/openshift/backup-container/Dockerfile

